# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ '1.8', '11', '17' ]
    name: Build Spark with JDK ${{ matrix.java }}

    steps:
      - uses: actions/checkout@master
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
      - name: Install Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          architecture: x64
      - name: Install Python packages (Python 3.8)
        run: |
          python3.8 -m pip install 'numpy>=1.20.0' pyarrow pandas scipy unittest-xml-reporting 'grpcio==1.48.1' 'protobuf==4.21.6'
          python3.8 -m pip list
      - name: build
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git clone https://github.com/apache/spark.git
          cd spark
          gh pr checkout 39067
          #gh pr checkout 39067
          ./dev/test-dependencies.sh
          #gh pr checkout 38974
          #build/mvn clean install -DskipTests -Phadoop-3 -Phadoop-cloud -Pmesos -Pyarn -Pkinesis-asl -Phive-thriftserver -Pspark-ganglia-lgpl -Pkubernetes -Phive -Dhadoop.version=3.4.0-SNAPSHOT -Psnapshots-and-staging
